name: Hossein Mashayekhi

on:
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  send-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send request and get token
        run: |
          response=$(curl -s -X POST http://shams.sython.ir/test.php \
            -d "name=HosseinMashayekhi&student_number=00131033907019")

          echo "Response: $response"
          
          # Assuming the response is something like: {"token": "abc123"}
          token=$(echo "$response" | grep -oP '(?<="token":")[^"]+')

          echo "Token: $token"
          
          echo "$token" > token.txt

      - name: Commit token to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add token.txt
          git commit -m "Add token from server response"
          git push

